Repository humanmade/altis-analytics, pull requests merged in 2022-04, with the labels that each got.

#254 Fix incorrect namespace usage
  inc/native/namespace.php
Labels: backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch, needs-test, backport v11-branch

#257 [Backport v9-branch] Fix incorrect namespace usage
  inc/native/namespace.php
Labels: backport v7-branch, backport v8-branch

#266 Update the docs with the max index age default value
  docs/native/api/server-side-api.md
Labels: backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch, backport v11-branch

#272 Update AWS Analytics to 4.6.0
  composer.json
Labels: backport v11-branch

#274 Fix flipped condition in Segment integration code
  inc/namespace.php
Labels: backport v11-branch

#280 Update Segment integration plugin
  composer.json
Labels: backport v11-branch
